### PR TITLE
steve big edits

### PR DESCRIPTION
**Pull request by steve-brett**
I've introduced php to manage pages (some still doesn't work)
and have done a fairly significant redesign.

### CODE REVIEW

**Comment by charliewilliams** [comment]
Wow, just saw this. Um… I guess we should merge it, hey?

**Comment by steve-brett** [comment]
hey sorry. I've been farting around on my own because i am a bad bad 
person. i will update

**Comment by charliewilliams** [comment]
Merged manually

**Comment by charliewilliams** [comment]
I merged this but I was thinking we could/should go to a github.io hosted
site, so that pushed commits are auto-deployed to the actual site. Good to
have everything distributed/public imo

**Comment by steve-brett** [comment]
yes that's a great idea. if things update in real time then i will no longer be led into temptation

**Comment by charliewilliams** [comment]
Hmm… it seems that we can't do it if we want to keep using the Victorian
technology of php:
http://stackoverflow.com/questions/10837946/how-to-publish-php-page-instead-of-html-at-github-to-demo-some-php-content

**Comment by steve-brett** [comment]
well, outdatedness is not the reason they claim there; rather that github doesn't run code. i like php and it makes a lot of sense to me. but i'm only using it as a way to simplify page layout editing, so i'm totally happy to revert back to having four static html pages. is there a more sensible way to have a master page layout that only needs to be edited once?

**Comment by charliewilliams** [comment]
Yes, that was just a dig. :)

On a quick googling, it doesn't look like there is such a thing— it's
either SSI or else copy-paste :/

**Comment by steve-brett** [comment]
well SSI should be fine in this case, I think.

**Comment by charliewilliams** [comment]
This looks good:
http://stackoverflow.com/questions/22326742/server-side-includes-alternative

**Comment by steve-brett** [comment]
big blue thumb

**Pull request closed without merging**
